### ISSUE TITLE
How to make SPA compatible?

### ISSUE THREAD

**Issue by eikaramba** [jitesoft/docker-lighttpd#3]
Although i am running Lighttpd on my dietpi server i am not that experienced with it. And even after Googling i did not found out how i can basically have something like https://github.com/SocialEngine/docker-nginx-spa just with your lovely alpine+lighttpd combo. I am refering to the fact that everything it routed to the root path so that i can just deploy my svelte SPA app with a index.html and still access  mydomain.com/sub/route which should serve the index.html and not tryint to access a /sub/route folder.

I am grateful for any help here, as i think this package is better suited for small containers instead of the bigger nginx combo.

**Comment by Johannestegner** [comment]
Hi!

You should be able to just mount (or copy) your application into the web-root of the lighty image and run it.
Basically:

```
FROM ghcr.io/jitesoft/lighttpd:latest

COPY ./ /var/www/html
```

I'm guessing that the issue you encounter is a configuration issue, where you actually have subfolders in your application which are named similar or the same as the actual routes?
Due to the nature of the webserver, we would want it to return stuff like images, css and javascript as well and not route it through the index file, so making a general rule where it _only_ hits the index file is a bit hard.

If I recall correctly, it _is_ possible to lock lighttpd do _only_ serve one file, but I have never tried that myself, and it would require you to serve your assets from another server.

If you wish to set up rewrite rules for specific routes, lighttpd have a [rewrite module](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs) which could be used. It have one piece you might want to take a closer look at if it's directories that is the issue:

https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModRewrite#urlrewrite-repeat-if-not-file

Can basically be used as:

```
url.rewrite-if-not-file = ( "" => "/index.html${url.path}${qsa}" )
```

**Comment by eikaramba** [comment]
ok i think i have it working now
```
"FROM jitesoft/lighttpd:latest", 
"COPY ./public /var/www/html", 
"COPY ./lighttpd.conf /etc/lighttpd/conf.d/000-default.conf", 
"RUN chmod -R 777 /var/www/html"
```

lighttpd.conf
```
server.modules += ("mod_access", "mod_accesslog", "mod_rewrite", "mod_auth", "mod_expire")
server.document-root = env.SERVER_ROOT
server.port = env.PORT
server.name = env.SERVER_NAME
server.username  = "www-data"
server.groupname = "www-data"
server.indexfiles = ("index.html")
server.max-fds = env.MAX_FDS
static-file.exclude-extensions = (".php", ".pl", ".cgi", ".fcgi",".env")
url.access-deny = ("~", ".inc")
$HTTP["url"] =~ "\/\..*" {
	url.access-deny = ( "" )
}
server.follow-symlink = "enable"
dir-listing.activate = "disable"
url.rewrite-once = (
  "^/(.+)[\.](css|js|html|gif|png|jpg|webp|avif|br)$" => "", #pass static files through
  "^/(.*)$" => "/index.html${url.path}${qsa}" #rewrite the rest
)
# url.rewrite-if-not-file = ( "" => "/" )


expire.mimetypes = (
	"text/plain" => "access plus 30 days",
	"text/css" => "access plus 30 days",
	"text/xml" => "access plus 30 days",
	"image/" => "access plus 30 days",
	"font/" => "access plus 30 days",
	"application/" => "access plus 30 days",
	"audio/" => "access plus 30 days",
	"video/" => "access plus 30 days"
)
```


strangely i don't get any logs in my caprover view, but that is too offtopic i think. thank you !

**Comment by eikaramba** [comment]
mhm unforunately that did not help. but appreciate you trying to help. 
![grafik](https://user-images.githubusercontent.com/1320525/178504185-74e4b8bc-a594-4a62-a59c-91a25ac0c60e.png)

**Comment by Johannestegner** [comment]
Been debugging this issue this morning. It seems like it's a permission issue that is the root of the problem. 
The user which runs the lighttpd process (www-data) is not able to output to /proc/1/fd/1 as it's owned by root, and changing the permission to output to it might be a bit of a security issue.

Trying to figure out the best way to handle this and will keep the issue open until it's solved.

Thank you!

**Comment by Johannestegner** [comment]
Closing in favor of #5 as the initial issue is solved here.
